// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCHgAJph-XMC-2Qo3beBp6CgQRme4pnUo',
    appId: '1:317367479932:web:5c1ece1b0df42ce152e3f9',
    messagingSenderId: '317367479932',
    projectId: 'eventfully-59447',
    authDomain: 'eventfully-59447.firebaseapp.com',
    storageBucket: 'eventfully-59447.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1mc3npamJi1qqS3KLQVSxC4HisuYXJWk',
    appId: '1:317367479932:android:e3bc72fc567c376552e3f9',
    messagingSenderId: '317367479932',
    projectId: 'eventfully-59447',
    storageBucket: 'eventfully-59447.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw6JVoBirFLwu-Eivemaw8YTinWHuIVmI',
    appId: '1:317367479932:ios:2d17c82c4d3d35b052e3f9',
    messagingSenderId: '317367479932',
    projectId: 'eventfully-59447',
    storageBucket: 'eventfully-59447.appspot.com',
    iosClientId: '317367479932-rngcn00vfud1q3tbdvlqepv9jcfc6lmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventfully',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw6JVoBirFLwu-Eivemaw8YTinWHuIVmI',
    appId: '1:317367479932:ios:2d17c82c4d3d35b052e3f9',
    messagingSenderId: '317367479932',
    projectId: 'eventfully-59447',
    storageBucket: 'eventfully-59447.appspot.com',
    iosClientId: '317367479932-rngcn00vfud1q3tbdvlqepv9jcfc6lmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventfully',
  );
}
